### ISSUE TITLE
Can't find gmail messages

### ISSUE THREAD

**Issue by mauricioszabo** [turbot/steampipe-plugin-googleworkspace#15]
**Describe the bug**
I can't find emails on gmail at all. Only return an empty set

**Steampipe version (`steampipe -v`)**
steampipe version 0.6.2

**Plugin version (`steampipe plugin list`)**
googleworkspace v0.0.2

**To reproduce**
```
steampipe query "select
       id,
       thread_id,
       internal_date,
       size_estimate,
       snippet
     from
       googleworkspace_gmail_my_message
     order by internal_date
     limit 10;
     "
+----+-----------+---------------+---------------+---------+
| id | thread_id | internal_date | size_estimate | snippet |
+----+-----------+---------------+---------------+---------+
+----+-----------+---------------+---------------+---------+
```

**Expected behavior**
To see 10 e-mails from my mailbox

**Comment by mauricioszabo** [comment]
Just found the problem: for some reason, my project didn't have access to the GMail API (nor the Drive API, to be honest, but the Drive API gave me an error and the GMail one silently failed).

Don't know if there's something to do here (maybe show an error like the drive API shows), but if you want, you can close this issue. Great work BTW :+1:

**Comment by e-gineer** [comment]
Great to know you are finding the plugin useful @mauricioszabo!

Was your error triggered because the APIs had not been used before / not been enabled? This is a bit different from not having permission - I'm wondering which case you hit here? I suspect the API was not enabled, because in that case we normally catch / ignore the error and return zero rows.

The reasoning is that since the API is not enabled there can't be any content. As opposed to other Google services (e.g. GCP), I guess that's not quite true in the specific case of email or some of these workspace items....

https://github.com/turbot/steampipe-plugin-googleworkspace/blob/main/googleworkspace/not_found.go#L16

**Comment by e-gineer** [comment]
Yes, I think we should. If the resources Cabot exist because the API is disabled then return zero rows. But if resources can be created while the API is disabled then we should return an error.

**Comment by cbruno10** [comment]
Hey @mauricioszabo , this has been fixed in https://github.com/turbot/steampipe-plugin-googleworkspace/commit/33e8ff2b87f12f6626f686221f70dab1ec800ff7 as part of v0.0.3.

Now, if the service API is disabled, the error will be shown to let you know the API needs to be enabled. If you see any other issues, please let us know!
